on:
  push:
    branches:
    - main
  pull_request:

name: check

defaults:
  run:
    working-directory: ./src-tauri

env:
  CARGO_TERM_COLOR: always
jobs:
  fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Tauri prerequisites
      # https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Create a mock aw-webui dist
        run: mkdir -p aw-webui/dist && touch aw-webui/dist/index.html
        working-directory: "."
      - name: Create a mock logo
        run: mkdir -p aw-webui/media/logo && convert -size 512x512 xc:white aw-webui/media/logo/logo.png
        working-directory: "."
      - run: cargo clippy --locked -- -D warnings
